[package]
name = "mozzzz"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", optional = true }
tokio = { version = "1.28.2", features = ["full"], optional = true }
rust-embed = { version = "6.4.2", optional = true }
thiserror = { version = "1.0.40", optional = true }
mime_guess = { version = "2.0.4", optional = true }

[features]
default = ["backend"]
backend = ["tokio", "axum", "rust-embed", "mime_guess", "thiserror"]
